name: Generate Snake Game

on:
  # Run once a day
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  # Also allow manual runs
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: Joseph1864
          outputs: dist/snake.svg

      - name: Push Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
